apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-discovery
  namespace: testapp
  labels:
    app: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: discovery
        image: rajuruppa6/discovery:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8761
      imagePullSecrets:
        - name: secret-devops